generating/generating: generating/generating.o \
					   include/parser/parser.o \
					   include/utility/display.o \
					   include/utility/shell.o \
					   include/utility/timer.o  \
					   generating/analysis_ctrl.o
