generating/generating: generating/generating.o \
					   include/parser/parser.o \
					   include/utility/display.o \
					   include/utility/shell.o \
					   include/utility/timer.o  \
					   include/utility/gzip.o \
					   include/models/WordMap.o \
					   include/models/StreamBuffer.o \
					   generating/analysis_ctrl.o \


